// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDNxbIhYfmiu5z0VemaSXqBgqhfyL24YY',
    appId: '1:1072903467056:web:f6bec27c188de4a8a23df5',
    messagingSenderId: '1072903467056',
    projectId: 'flutterfashionv2',
    authDomain: 'flutterfashionv2.firebaseapp.com',
    storageBucket: 'flutterfashionv2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpncjspuFVLXx2UBJ-6craF2HtvM6rEwo',
    appId: '1:1072903467056:android:58c9c3ddb93a54a3a23df5',
    messagingSenderId: '1072903467056',
    projectId: 'flutterfashionv2',
    storageBucket: 'flutterfashionv2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWCkQLKefLNQxher2nV7qtHBIEZIWTltQ',
    appId: '1:1072903467056:ios:1ee55095e797e81da23df5',
    messagingSenderId: '1072903467056',
    projectId: 'flutterfashionv2',
    storageBucket: 'flutterfashionv2.firebasestorage.app',
    iosBundleId: 'com.example.flutterfashionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWCkQLKefLNQxher2nV7qtHBIEZIWTltQ',
    appId: '1:1072903467056:ios:1ee55095e797e81da23df5',
    messagingSenderId: '1072903467056',
    projectId: 'flutterfashionv2',
    storageBucket: 'flutterfashionv2.firebasestorage.app',
    iosBundleId: 'com.example.flutterfashionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDNxbIhYfmiu5z0VemaSXqBgqhfyL24YY',
    appId: '1:1072903467056:web:6fb787214de6a0a1a23df5',
    messagingSenderId: '1072903467056',
    projectId: 'flutterfashionv2',
    authDomain: 'flutterfashionv2.firebaseapp.com',
    storageBucket: 'flutterfashionv2.firebasestorage.app',
  );
}
